text_sensor:
  - platform: teleinfo
    tag_name: "NGTF"
    name: "Type de contrat"
    id: ngtf
    teleinfo_id: myteleinfo

  - platform: teleinfo
    tag_name: "LTARF"
    name: "Tarif en cours"
    id: ltarf
    teleinfo_id: myteleinfo

  - platform: teleinfo
    tag_name: "PJOURF+1"
    name: "Profil tarifaire prévu demain"
    id: pjourf_plus1
    teleinfo_id: myteleinfo

  - platform: teleinfo
    tag_name: "PPOINTE"
    name: "Jour de pointe prévu demain"
    id: ppointe
    teleinfo_id: myteleinfo

sensor:
  # Informations TIC
  # Index énergie par contrat
  - platform: teleinfo
    tag_name: "EAST"
    name: "Énergie totale soutirée"
    unit_of_measurement: "Wh"
    id: east
    teleinfo_id: myteleinfo

  - platform: teleinfo
    tag_name: "EAIT"
    name: "Énergie totale injectée"
    unit_of_measurement: "Wh"
    id: eait
    teleinfo_id: myteleinfo

  - platform: teleinfo
    tag_name: "EASF01"
    name: "Énergie période 1"
    unit_of_measurement: "Wh"
    id: easf01
    teleinfo_id: myteleinfo

  - platform: teleinfo
    tag_name: "EASF02"
    name: "Énergie période 2"
    unit_of_measurement: "Wh"
    id: easf02
    teleinfo_id: myteleinfo

  - platform: teleinfo
    tag_name: "EASF03"
    name: "Énergie période 3"
    unit_of_measurement: "Wh"
    id: easf03
    teleinfo_id: myteleinfo

  - platform: teleinfo
    tag_name: "EASF04"
    name: "Énergie période 4"
    unit_of_measurement: "Wh"
    id: easf04
    teleinfo_id: myteleinfo

  - platform: teleinfo
    tag_name: "EASF05"
    name: "Énergie période 5"
    unit_of_measurement: "Wh"
    id: easf05
    teleinfo_id: myteleinfo

  - platform: teleinfo
    tag_name: "EASF06"
    name: "Énergie période 6"
    unit_of_measurement: "Wh"
    id: easf06
    teleinfo_id: myteleinfo

  # Courants par phase
  - platform: teleinfo
    tag_name: "IRMS1"
    name: "Courant phase 1"
    unit_of_measurement: "A"
    id: irms1
    teleinfo_id: myteleinfo

  - platform: teleinfo
    tag_name: "IRMS2"
    name: "Courant phase 2"
    unit_of_measurement: "A"
    id: irms2
    teleinfo_id: myteleinfo

  - platform: teleinfo
    tag_name: "IRMS3"
    name: "Courant phase 3"
    unit_of_measurement: "A"
    id: irms3
    teleinfo_id: myteleinfo

  # Tensions par phase
  - platform: teleinfo
    tag_name: "URMS1"
    name: "Tension phase 1"
    unit_of_measurement: "V"
    id: urms1
    teleinfo_id: myteleinfo

  - platform: teleinfo
    tag_name: "URMS2"
    name: "Tension phase 2"
    unit_of_measurement: "V"
    id: urms2
    teleinfo_id: myteleinfo

  - platform: teleinfo
    tag_name: "URMS3"
    name: "Tension phase 3"
    unit_of_measurement: "V"
    id: urms3
    teleinfo_id: myteleinfo

  # Puissance instantanée
  - platform: teleinfo
    tag_name: "SINSTS"
    name: "Puissance apparente totale"
    unit_of_measurement: "VA"
    id: sinsts
    teleinfo_id: myteleinfo

  - platform: teleinfo
    tag_name: "SINST1"
    name: "Puissance phase 1"
    unit_of_measurement: "VA"
    id: sinst1
    teleinfo_id: myteleinfo

  - platform: teleinfo
    tag_name: "SINST2"
    name: "Puissance phase 2"
    unit_of_measurement: "VA"
    id: sinst2
    teleinfo_id: myteleinfo

  - platform: teleinfo
    tag_name: "SINST3"
    name: "Puissance phase 3"
    unit_of_measurement: "VA"
    id: sinst3
    teleinfo_id: myteleinfo

  # Puissance max du jour
  - platform: teleinfo
    tag_name: "SMAXSN"
    name: "Puissance max totale"
    unit_of_measurement: "VA"
    id: smaxsn
    teleinfo_id: myteleinfo

  - platform: teleinfo
    tag_name: "SMAXSN1"
    name: "Puissance max phase 1"
    unit_of_measurement: "VA"
    id: smaxsn1
    teleinfo_id: myteleinfo

  - platform: teleinfo
    tag_name: "SMAXSN2"
    name: "Puissance max phase 2"
    unit_of_measurement: "VA"
    id: smaxsn2
    teleinfo_id: myteleinfo

  - platform: teleinfo
    tag_name: "SMAXSN3"
    name: "Puissance max phase 3"
    unit_of_measurement: "VA"
    id: smaxsn3
    teleinfo_id: myteleinfo

  # Autres
  - platform: teleinfo
    tag_name: "PCOUP"
    name: "Puissance de coupure"
    unit_of_measurement: "VA"
    id: pcoup
    teleinfo_id: myteleinfo

  - platform: teleinfo
    tag_name: "PREF"
    name: "Puissance de référence"
    unit_of_measurement: "kVA"
    id: pref
    teleinfo_id: myteleinfo

  - platform: teleinfo
    tag_name: "CCASN"
    name: "Compteur de dépassement"
    id: ccasn
    teleinfo_id: myteleinfo

  - platform: teleinfo
    tag_name: "NTARF"
    name: "Index tarifaire en cours"
    id: ntarf
    teleinfo_id: myteleinfo

  - platform: teleinfo
    tag_name: "NJOURF"
    name: "Jour tarifaire actuel"
    id: njourf
    teleinfo_id: myteleinfo

  - platform: teleinfo
    tag_name: "NJOURF+1"
    name: "Jour tarifaire prévu demain"
    id: njourf_plus1
    teleinfo_id: myteleinfo
